CREATE TABLE IF NOT EXISTS user (
  no INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(256) UNIQUE NOT NULL,
  password VARCHAR(256) NOT NULL
);


CREATE TABLE oauth_client_details (
  `no` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  client_id VARCHAR(256),
  client_secret VARCHAR(256)
);


CREATE TABLE oauth_access_token (
  `no` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `value` VARCHAR(256) NOT NULL,
  user_no INT(11) UNSIGNED,
  client_no INT(11) UNSIGNED,
  refresh_token_no INT(11) UNSIGNED
);

CREATE TABLE oauth_refresh_token (
  `no` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `value` VARCHAR(256) NOT NULL
);

CREATE TABLE oauth_approvals (
  `no` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_no INT(11) UNSIGNED,
  client_no INT(11) UNSIGNED,
  scope VARCHAR(256),
  `status` VARCHAR(10),
  expires_at TIMESTAMP,
  lastModified_at TIMESTAMP
);